(source gnu)
(source melpa)
(source marmalade)
(source SC)
(source org)

(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "afternoon-theme")
(depends-on "base16-theme")
(depends-on "color-theme-solarized")
(depends-on "column-marker")
(depends-on "company")
(depends-on "dash-at-point")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "exec-path-from-shell")
(depends-on "feature-mode")
(depends-on "flatui-theme")
(depends-on "flx-ido")
(depends-on "flymake-ruby")
(depends-on "flymake-rust")
(depends-on "git-gutter-fringe")
(depends-on "inf-ruby")
(depends-on "js2-mode")
(depends-on "magit" :git "https://github.com/magit/magit.git")
(depends-on "markdown-mode")
(depends-on "minitest" :git "https://github.com/unders/minitest-emacs.git")
(depends-on "niflheim-theme")
(depends-on "noctilux-theme")
(depends-on "pallet" "0.6")
(depends-on "paredit")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "rainbow-mode")
(depends-on "rbenv")
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "rust-mode")
(depends-on "simple-httpd")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "skewer-mode")
(depends-on "tern")
(depends-on "tern-auto-complete")
(depends-on "toml-mode")
(depends-on "wgrep" :git "https://github.com/mhayashi1120/Emacs-wgrep.git")
(depends-on "yaml-mode")
(depends-on "yari")
(depends-on "zenburn-theme")
